<?php
/*
8/21/10 initial version
8/24/10 "written" added
8/29/10 convert to array
12/3/10 get_text functions added
*/
$nature = get_text("Nature");			// 12/03/10
$disposition = get_text("Disposition");
$patient = get_text("Patient");
$incident = get_text("Incident");
$incidents = get_text("Incidents");

$capts = array(
"911 Contacted",
"A",
"About this version ...",
"Add Action",
"Add Facility",
"Add note",
"Add {$patient}",
"Add Unit",
"Add user",
"Add/Edit Notifies",
"Addr",
"admin",
"Alarm audio test",
"All-Tickets Notify",
"As of",
"Board",
"Cancel",
"Capability",
"Change display",
"Chat",
"City",
"Clear",
"Close incident",
"Config",
"Constituents",
"Contact email",
"Contact name",
"Contact phone",
"Contacts",
"Current situation",
"Delete Closed Tickets",
"Description",
"Dispatch Unit",
"Dispatched",
"{$disposition}",
"Dump DB to screen",
"E-mail",
"Edit My Profile",
"Edit Settings",
"Email users",
"Fac's",
"Facility arrive time",
"Facility clear time",
"Facility en-route time",
"Facility Status",
"Facility Types",
"Facility",
"Handle",
"Help",
"High",
"ID",
"{$incident} Lat/Lng",
"{$incident} name",
"{$incident} types",
"{$incident}",
"Lat/Lng",
"Links",
"Location",
"Log In",
"Log",
"Logged in",
"Logout",
"Medium",
"Mobile",
"Module",
"mouseover caption for help informati",
"Name",
"{$nature}",
"New",
"Next",
"Normal",
"Notify",
"On-scene",
"Opening hours",
"Optimize Database",
"P",
"Password",
"Perm's",
"Phone",
"Popup",
"Position",
"Primary pager",
"Print",
"Priority",
"Protocol",
"Reported by",
"Reports",
"Reset Database",
"Responding",
"Run End",
"Run Start",
"Scheduled Date",
"Search",
"Security contact",
"Security email",
"Security phone",
"Security reqs",
"Severities",
"Situation",
"SOP's",
"Sort",
"St",
"Status",
"Synopsis",
"This Call",
"Time",
"Type",
"U",
"Unit status types",
"Unit types",
"Unit",
"Units",
"Updated",
"User",
"Written",
"USNG");
?>