<?php
/**
 *
 *
 * @package capts.inc.php
 * @author John Doe <john.doe@example.com>
 * @since version
 * @version string
 */

error_reporting(E_ALL);		// 10/1/08

/*
8/21/10 initial version
8/24/10 "written" added
8/29/10 convert to array
12/3/10 get_text functions added
2/9/12 get_text functions removed, list lengthened with Patient, etc., strings
3/2/12 corrected "Full name" array element punctuation
3/4/12 corrected line 73 missing comma, {}
*/

$capts = array(
gettext("911 Contacted"),
gettext("A"),
gettext("About this version"),
gettext("Add Action"),
gettext("Add Facility"),
gettext("Add note"),
gettext("Add patient"),
gettext("Add Unit"),
gettext("Add user"),
gettext("Add/Edit Notifies"),
gettext("Addr"),
gettext("admin"),
gettext("Alarm audio test"),
gettext("All-Tickets Notify"),
gettext("As of"),
gettext("Board"),
gettext("Cancel"),
gettext("Capability"),
gettext("Change display"),
gettext("Chat"),
gettext("City"),
gettext("Clear"),
gettext("Close incident"),
gettext("Config"),
gettext("Constituents"),
gettext("Contact email"),
gettext("Contact name"),
gettext("Contact phone"),
gettext("Contacts"),
gettext("Current situation"),
gettext("Date of birth"),
gettext("Delete Closed Tickets"),
gettext("Description"),
gettext("Dispatch Unit"),
gettext("Dispatched"),
gettext("Disposition"),
gettext("Dump DB to screen"),
gettext("E-mail"),
gettext("Edit My Profile"),
gettext("Edit Settings"),
gettext("Email users"),
gettext("Fac's"),
gettext("Facility arrive time"),
gettext("Facility clear time"),
gettext("Facility contact"),
gettext("Facility en-route time"),
gettext("Facility Status"),
gettext("Facility Types"),
gettext("Facility"),
gettext("Full name"),
gettext("Gender"),
gettext("Handle"),
gettext("Help"),
gettext("High"),
gettext("ID"),
gettext("Incident Lat/Lng"),
gettext("Incident name"),
gettext("Incident types"),
gettext("Incident"),
gettext("Incidents"),
gettext("Insurance"),
gettext("Lat/Lng"),
gettext("Links"),
gettext("Location"),
gettext("Log In"),
gettext("Log"),
gettext("Logged in"),
gettext("Logout"),
gettext("Medium"),
gettext("Mobile"),
gettext("Module"),
gettext("mouseover caption for help information"),
gettext("Name"),
gettext("Nature"),
gettext("New"),
gettext("Next"),
gettext("Normal"),
gettext("Notify"),
gettext("On-scene"),
gettext("Opening hours"),
gettext("Optimize Database"),
gettext("P"),
gettext("Patient"),
gettext("Patient ID"),
gettext("Password"),
gettext("Permissions"),
gettext("Phone"),
gettext("Popup"),
gettext("Position"),
gettext("Primary pager"),
gettext("Print"),
gettext("Priority"),
gettext("Protocol"),
gettext("Reported by"),
gettext("Reports"),
gettext("Reset Database"),
gettext("Responding"),
gettext("Run End"),
gettext("Run Start"),
gettext("Scheduled Date"),
gettext("Search"),
gettext("Security contact"),
gettext("Security email"),
gettext("Security phone"),
gettext("Security reqs"),
gettext("Severities"),
gettext("Situation"),
gettext("SOP's"),
gettext("Sort"),
gettext("St"),
gettext("Status"),
gettext("Synopsis"),
gettext("This Call"),
gettext("Time"),
gettext("Type"),
gettext("U"),
gettext("Unit status types"),
gettext("Unit types"),
gettext("Unit"),
gettext("Units"),
gettext("Updated"),
gettext("User"),
gettext("USNG"),
gettext("Written")
);
